import type { SgNode } from '@ast-grep/napi';
import type { RawCallSite } from '../graph/types';

/**
 * AST node kinds that represent a call across the languages we support.
 * Used by `findInnerCall` to detect chained calls — `x.a().b()` — by
 * checking whether a callee node's children include a nested invocation.
 */
const CALL_KINDS = new Set([
    'call_expression', // TS, JS, Kotlin, Scala, Swift, Rust, Go, C, C++, Dart, Java(some grammars)
    'call', // Python, Ruby
    'method_invocation', // Java
    'invocation_expression', // C#
    'function_call_expression', // PHP bare call
    'member_call_expression', // PHP $obj->method()
    'scoped_call_expression', // PHP Foo::bar()
]);

/**
 * Given a callee/function node, returns the inner call expression it
 * receives on (i.e. for `repo.find(1).greet`, called with the outer
 * member_expression, returns the `repo.find(1)` call_expression). Returns
 * null when the callee doesn't receive on another call.
 */
export function findInnerCall(callee: SgNode): SgNode | null {
    for (const c of callee.children()) {
        if (CALL_KINDS.has(String(c.kind()))) {
            return c;
        }
    }
    return null;
}

/**
 * Compute the column convention used by call-site extraction (= end of the
 * call's function/callee field). For chained calls we need the inner call's
 * column to thread `chainedFromColumn` so the resolver can join the chain.
 */
export function callColumn(call: SgNode): { line: number; column: number } {
    const fn = call.field('function');
    if (fn) {
        return fn.range().end;
    }
    // PHP-style nodes don't expose a `function` field — fall back to the call
    // node's start. The resolver matches on (line, column) keys generated by
    // the per-language extractor, so consistency within a language matters
    // more than absolute uniformity across grammars.
    return call.range().start;
}

/**
 * Language-specific configuration for call extraction.
 * Each language provides its self/super patterns and how to find class context in the AST.
 *
 * Note: noise filtering is intentionally NOT performed at extraction time.
 * The resolver applies the per-language noise filter AFTER the receiver-type
 * tier (`src/resolver/call-resolver.ts`) so user-domain calls like
 * `user.update()` — where `update` is in a language noise list but
 * `UserService.update` exists in the symbol table — aren't dropped before
 * they can be resolved. Dropping noise at extraction would kill that tier.
 */
export interface CallExtractionConfig {
    /** Prefixes indicating a self-reference (e.g., 'self.', 'this.') */
    selfPrefixes: string[];
    /** Prefixes indicating a super-reference (e.g., 'super().', 'super.', 'base.') */
    superPrefixes: string[];
    /** Find the enclosing class/module/impl node from a call site */
    findEnclosingClass: (node: SgNode) => SgNode | null;
    /** Extract the parent class name from a class node (for super resolution) */
    getParentClass?: (classNode: SgNode) => string | undefined;
    /** Skip this callee entirely (e.g., TS skips this.field.method — handled by DI) */
    skipCallee?: (callee: string) => boolean;
    /**
     * Optional: derive a diField from the callee text. When set, every call
     * with a single-segment receiver (e.g., `repo.find` or `this.repo.find`)
     * threads that segment as `diField`. The resolver only routes through DI
     * if the field is in the file's diMap, so non-DI identifiers fall through
     * harmlessly to receiver/import/unique tiers.
     */
    extractDiField?: (callee: string) => string | undefined;
}

/**
 * Shared call extraction for all languages.
 *
 * Parses `$CALLEE($$$ARGS)` pattern, detects self/super references
 * based on language config, and populates resolveInClass for
 * class-aware resolution downstream.
 */
export function extractCalls(rootNode: SgNode, fp: string, config: CallExtractionConfig, calls: RawCallSite[]): void {
    for (const m of rootNode.findAll('$CALLEE($$$ARGS)')) {
        const calleeNode = m.getMatch('CALLEE');
        const callee = calleeNode?.text();
        if (!callee) {
            continue;
        }
        if (config.skipCallee?.(callee)) {
            continue;
        }

        const callName = callee.includes('.') ? callee.split('.').pop()! : callee;

        let resolveInClass: string | undefined;

        // Check self-reference: callee must be exactly `prefix + methodName` (no further chaining)
        for (const prefix of config.selfPrefixes) {
            if (!callee.startsWith(prefix)) {
                continue;
            }
            const rest = callee.substring(prefix.length);
            if (rest.includes('.')) {
                break; // chained access (e.g., this.field.method) — not a self call
            }
            const classNode = config.findEnclosingClass(m);
            resolveInClass = classNode?.field('name')?.text();
            break;
        }

        // Check super-reference if no self match
        if (!resolveInClass) {
            for (const prefix of config.superPrefixes) {
                const matches =
                    callee === prefix || (callee.startsWith(prefix) && !callee.substring(prefix.length).includes('.'));
                if (!matches) {
                    continue;
                }
                const classNode = config.findEnclosingClass(m);
                if (classNode && config.getParentClass) {
                    resolveInClass = config.getParentClass(classNode);
                }
                break;
            }
        }

        const diField = resolveInClass ? undefined : config.extractDiField?.(callee);

        // Column convention: end-of-callee text (≈ position of `(` in args).
        // For `repo.find(1)` it's the col after `find`. For `repo.find(1).greet()`
        // (the OUTER chained call) it's the col after `greet` — distinct from
        // the inner `find` call. Without this, both calls share the receiver-
        // start column and chained calls collide on receiver-type lookup.
        const calleeEnd = calleeNode?.range().end;
        const line = calleeEnd?.line ?? m.range().start.line;
        const column = calleeEnd?.column ?? m.range().start.column;

        // Chain detection: if the callee receives on another call (`x.a().b`
        // — the callee of `b` is a member_expression whose object is the
        // call to `a`), record the inner call's location so the resolver
        // can pick up the chain in its second pass.
        let chainedFromLine: number | undefined;
        let chainedFromColumn: number | undefined;
        if (calleeNode) {
            const inner = findInnerCall(calleeNode);
            if (inner) {
                const innerCol = callColumn(inner);
                chainedFromLine = innerCol.line;
                chainedFromColumn = innerCol.column;
            }
        }

        calls.push({
            source: fp,
            callName,
            line,
            column,
            ...(resolveInClass ? { resolveInClass } : {}),
            ...(diField ? { diField } : {}),
            ...(chainedFromLine !== undefined ? { chainedFromLine, chainedFromColumn } : {}),
        });
    }
}
