#!/usr/bin/env bun
/**
 * Generate docs/language-support-matrix.md from LANGUAGE_SUPPORT.
 * Run: `bun run docs:matrix`
 *
 * Writes a human-readable markdown table that GitHub renders in the doc
 * tree. CI can re-run this and diff to catch un-regenerated docs.
 */
import { writeFileSync } from 'fs';
import { LANGUAGE_SUPPORT } from '../src/languages/support-matrix';
import type { LanguageSupportRecord } from '../src/languages/support-matrix-schema';

const TIER_ICON: Record<LanguageSupportRecord['tier'], string> = {
    full: '🟢',
    basic: '🟡',
    experimental: '🔴',
};

const PARSE_ICON: Record<LanguageSupportRecord['parse_speed'], string> = {
    fast: '⚡',
    moderate: '🚶',
    slow: '🐢',
};

const RECEIVER_LABEL: Record<LanguageSupportRecord['features']['receiver_type'], string> = {
    none: '—',
    'scope-local': 'scope-local',
    'class+init': 'class+init',
    factory: 'factory',
    full: 'full',
};

function tick(b: boolean): string {
    return b ? '✓' : '—';
}

function renderRow(r: LanguageSupportRecord): string {
    return [
        '',
        r.display_name,
        `${TIER_ICON[r.tier]} ${r.tier}`,
        `${PARSE_ICON[r.parse_speed]} ${r.parse_speed}`,
        tick(r.features.noise),
        tick(r.features.capabilities),
        tick(r.features.di_heuristic),
        RECEIVER_LABEL[r.features.receiver_type],
        tick(r.features.complexity_kinds),
        tick(r.features.imports),
        r.canonical_fixture ? `\`${r.canonical_fixture}\`` : '—',
        '',
    ].join(' | ');
}

function render(): string {
    const lines: string[] = [];
    lines.push('# Language Support Matrix');
    lines.push('');
    lines.push('> Auto-generated from `src/languages/support-matrix.ts` via `bun run docs:matrix`.');
    lines.push('> Do not edit this file by hand — changes will be overwritten.');
    lines.push('');
    lines.push('## Legend');
    lines.push('');
    lines.push(
        "- **Tier**: 🟢 full = validated on a real open-source repo ≥10k LOC, features registered. 🟡 basic = unit-tested on fixtures, no real-repo validation. 🔴 experimental = registered but not exercised on real code.",
    );
    lines.push(
        '- **Parse speed**: ⚡ fast (<50ms avg/file), 🚶 moderate (50-500ms), 🐢 slow (>500ms).',
    );
    lines.push(
        '- **Receiver type**: `scope-local` covers `const x = new Foo()`; `class+init` adds class attribute + `__init__` typed-param hints; `factory` is Go-style `x := NewFoo()`; `full` implies flow analysis (currently nowhere).',
    );
    lines.push('');
    lines.push('## Matrix');
    lines.push('');
    lines.push(
        '| Language | Tier | Parse | Noise | Capabilities | DI heuristic | Receiver-type | Complexity | Imports | Canonical fixture |',
    );
    lines.push('|---|---|---|---|---|---|---|---|---|---|');
    for (const r of LANGUAGE_SUPPORT) {
        lines.push(renderRow(r));
    }
    lines.push('');
    lines.push('## Per-language notes');
    lines.push('');
    for (const r of LANGUAGE_SUPPORT) {
        if (r.notes.length === 0) {
            continue;
        }
        lines.push(`### ${r.display_name} (\`${r.key}\`)`);
        lines.push('');
        for (const note of r.notes) {
            lines.push(`- ${note}`);
        }
        lines.push('');
    }
    lines.push('## Baselines');
    lines.push('');
    lines.push(
        'Languages in the 🟢 full tier have recorded baseline `tier_distribution` ratios. CI parses a canonical fixture and asserts ratios fall within bands. Regressions fail the build.',
    );
    lines.push('');
    lines.push(
        '| Language | resolved_min | ambiguous_max | receiver/1k | di/1k | high_conf_min |',
    );
    lines.push('|---|---|---|---|---|---|');
    for (const r of LANGUAGE_SUPPORT) {
        if (!r.baseline_tier_ratios) {
            continue;
        }
        const b = r.baseline_tier_ratios;
        lines.push(
            `| ${r.display_name} | ${b.resolved_min} | ${b.ambiguous_max} | ${b.receiver_min_per_1k_nodes} | ${b.di_min_per_1k_nodes} | ${b.high_conf_min_ratio} |`,
        );
    }
    lines.push('');
    return lines.join('\n');
}

const output = render();
writeFileSync('docs/language-support-matrix.md', output);
console.log(`wrote docs/language-support-matrix.md (${output.length} bytes)`);
